### ISSUE TITLE
Rotating drum with post-processing example is now useless

### ISSUE THREAD

**Issue by blaisb** [chaos-polymtl/lethe#1003]
We have an example (this one https://lethe-cfd.github.io/lethe/documentation/examples/dem/rotating-drum-with-postprocessing/rotating-drum-with-postprocessing.html) which is literally useless since it only adds a single line and does not add any new interpretation or animations. It should be deprecated and removed

**Comment by nick0413** [comment]
On this issue, i have been trying to run the small rotating drum example but i get the following error. 

`An error occurred in line <700> of file </home/nick0413/Software/lethe/git/source/core/utilities.cc> in function                                                                                                                                     int get_max_number_of_boundary_conditions(const string&)                                                                                                                                                                                     The violated condition was:                                                                                                                                                                                                                          max_number_of_boundary_conditions >= 0                                                                                                                                                                                                       Additional information:                                                                                                                                                                                                                              Your parameter file does not contain any indication for the number of                                                                                                                                                                            boundary conditions for any physics supported by Lethe. Since November                                                                                                                                                                           2023, Lethe requires that a "boundary conditions" subsection is                                                                                                                                                                                  present with at least "number=0"                                                                                                                                                                                                                                                                                                                                                                                                                                                              Stacktrace: `

Im thinking the entire example is outdated

**Comment by blaisb** [comment]
Have you updated to the latest version of lethe? The parameter file for this example works fine with the current version ( I am running the example right now on my desktop computer)

**Comment by nick0413** [comment]
Oh, then it must be a problem with my install then. I followed the install
guide for WSL last Monday, so I figured it is the updated version
