### ISSUE TITLE
Relicensing Lethe

### ISSUE THREAD

**Issue by blaisb** [chaos-polymtl/lethe#1145]
During this week's Hackathon we discussed relicensing for Lethe in order to increase the flexibility of our license and also to remain coherent with the license that is used by deal.II.

Deal.II uses a dual license under: Apache-2.0 WITH LLVM-exception OR LGPL-2.1-or-later
I propose we use the same license.

One of the main target of this issue is to gather an OK from every past and present contributers (meaning anyone that has ever commited a file or a change to Lethe).

@AmishgaAlphonius 
@shahabgol 
@oguevremont 
@Luckabarbeau 
@voferreira 
@CaroleAnneDaunais 
@acdaigneault 
@jeannejoachim 
@OGaboriault 
@hepap 
@tonielgeitani 
@paulapatience 
@PierreLaurentinCS 
@ghazalemir 
@technophil98 
@SGauvin 
@bibeauv 
@mivaia 
@emilebergeron 
@cenr20 
@OresteMarquis 
@charles-lp 
@Wendi-L 
@Clara-Haydar 
@maxl-1 
@Wieb-ke 
@anicusan 
@EduardsBlandin 
@yashuuzi 
@kronbichler 
@bangerth 
@Raju1231

**Comment by peterrum** [comment]
> gather an OK from every past and present contributers.

OK from my side :+1:

**Comment by paulapatience** [comment]
OK for me too.

**Comment by lpsaavedra** [comment]
OK

**Comment by bangerth** [comment]
I don't even remember contributing, but of course it's ok with me :-)

**Comment by blaisb** [comment]
> I don't even remember contributing, but of course it's ok with me :-)

You did, you fixed a few typos in the README.md file 4 years ago. Everybody's equal, it needs to be fair :)

**Comment by voferreira** [comment]
Ok

**Comment by CaroleAnneDaunais** [comment]
Ok ✌

**Comment by anicusan** [comment]
Thanks for including me as a contributor - of course, very happy with the relicensing!

**Comment by OresteMarquis** [comment]
Ok :)

**Comment by ghazalemir** [comment]
Ok :)

**Comment by oguevremont** [comment]
Ok!

**Comment by acdaigneault** [comment]
Ok!

**Comment by kronbichler** [comment]
Ok

**Comment by OGaboriault** [comment]
Ok

**Comment by bangerth** [comment]
On 5/16/24 12:46, Bruno Blais wrote:
> You did, you fixed a few typos in the README.md file 4 years ago. Everybody's 
> equal, it needs to be fair :)

My version of "see something say something": See a typo anywhere, write a pull 
request :-)

**Comment by Luckabarbeau** [comment]
Ok !

**Comment by yashuuzi** [comment]
Ok!

**Comment by AmishgaAlphonius** [comment]
Ok :)

**Comment by Wieb-ke** [comment]
ok

**Comment by PierreLaurentinCS** [comment]
Ok for me !

**Comment by charles-lp** [comment]
Ok for me as well!

**Comment by tonielgeitani** [comment]
Okay for me  :)On May 16, 2024, at 20:24, Charles Le Pailleur ***@***.***> wrote:﻿
Ok for me as well!

**Comment by Clara-Haydar** [comment]
Ok :)

________________________________
From: Bruno Blais ***@***.***>
Sent: Thursday, May 16, 2024 8:43:54 PM
To: chaos-polymtl/lethe ***@***.***>
Cc: Clara-Haydar ***@***.***>; Mention ***@***.***>
Subject: [chaos-polymtl/lethe] Relicensing Lethe (Issue #1145)


During this week's Hackathon we discussed relicensing for Lethe in order to increase the flexibility of our license and also to remain coherent with the license that is used by deal.II.

Deal.II uses a dual license under: Apache-2.0 WITH LLVM-exception OR LGPL-2.1-or-later
I propose we use the same license.

One of the main target of this issue is to gather an OK from every past and present contributers.

@AmishgaAlphonius<https://github.com/AmishgaAlphonius>
@shahabgol<https://github.com/shahabgol>
@oguevremont<https://github.com/oguevremont>
@Luckabarbeau<https://github.com/Luckabarbeau>
@voferreira<https://github.com/voferreira>
@CaroleAnneDaunais<https://github.com/CaroleAnneDaunais>
@acdaigneault<https://github.com/acdaigneault>
@jeannejoachim<https://github.com/jeannejoachim>
@OGaboriault<https://github.com/OGaboriault>
@hepap<https://github.com/hepap>
@tonielgeitani<https://github.com/tonielgeitani>
@paulapatience<https://github.com/paulapatience>
@PierreLaurentinCS<https://github.com/PierreLaurentinCS>
@ghazalemir<https://github.com/ghazalemir>
@technophil98<https://github.com/technophil98>
@SGauvin<https://github.com/SGauvin>
@bibeauv<https://github.com/bibeauv>
@mivaia<https://github.com/mivaia>
@emilebergeron<https://github.com/emilebergeron>
@cenr20<https://github.com/cenr20>
@OresteMarquis<https://github.com/OresteMarquis>
@charles-lp<https://github.com/charles-lp>
@Wendi-L<https://github.com/Wendi-L>
@Clara-Haydar<https://github.com/Clara-Haydar>
@maxl-1<https://github.com/maxl-1>
@Wieb-ke<https://github.com/Wieb-ke>
@anicusan<https://github.com/anicusan>
@EduardsBlandin<https://github.com/EduardsBlandin>
@yashuuzi<https://github.com/yashuuzi>
@kronbichler<https://github.com/kronbichler>
@bangerth<https://github.com/bangerth>
@Raju1231<https://github.com/Raju1231>

**Comment by Wendi-L** [comment]
Many thanks for including me as a contributor. I fully support the relicensing.

**Comment by hepap** [comment]
Ok for me :)

**Comment by jeannejoachim** [comment]
Hi Lethe family!

Thank you Bruno for checking that with all of us. I do not know enough
about licencing to get what will change specifically from the current
LGPL-2.1, but I see Apache-2.0 WITH LLVM-exception is still a free software
license (so not a major change on this part), and so I trust deal.II and
the current Lethe team judgment about the licence to use 🙂

Have a good day!

Jeanne

**Comment by mivaia** [comment]
Ok for me!

**Comment by SGauvin** [comment]
Ok from my side 👋

**Comment by technophil98** [comment]
No problem on my side!
Sorry for the delay. No notifications were sent for this issue.
